import type { SlurpSettings } from "../settings/slp-settings-contract";
import {
  slpBackstageSectionFor,
  type SlpBackstageSection,
  type SlpBackstageTarget,
} from "../../base/navigation/slp-backstage-target";

export type SlpBackstageScope = "all-slurp" | "this-viewer" | "new-creators" | "creator";
export type SlpBackstagePlacement = {
  section: SlpBackstageSection;
  target: SlpBackstageTarget;
  scope: SlpBackstageScope;
  searchTerms: readonly string[];
  /** Runtime or setup state with no Backstage control; hidden from search and exempt from anchors. */
  internal?: true;
};

const place = (
  section: SlpBackstageSection,
  target: SlpBackstageTarget,
  scope: SlpBackstageScope,
  ...searchTerms: string[]
): SlpBackstagePlacement => ({ section: slpBackstageSectionFor(section, target), target, scope, searchTerms });
const world = (target: SlpBackstageTarget, ...terms: string[]) => place("world", target, "all-slurp", ...terms);
const content = (target: SlpBackstageTarget, ...terms: string[]) => place("content", target, "all-slurp", ...terms);
const automation = (target: SlpBackstageTarget, ...terms: string[]) =>
  place("automation", target, "all-slurp", ...terms);
const internal = (placement: SlpBackstagePlacement): SlpBackstagePlacement => ({ ...placement, internal: true });
const prompts = (...terms: string[]) => place("prompts", "prompts", "all-slurp", ...terms);
const maintenance = (...terms: string[]) => place("maintenance", "autopurge", "all-slurp", ...terms);

/** One searchable, canonical Backstage home for every persisted setting. */
export const SLP_BACKSTAGE_SETTING_PLACEMENT: Record<keyof SlurpSettings, SlpBackstagePlacement> = {
  inlineAdsEnabled: world("ads", "ads", "promotions", "feed"),
  inlineAdsFrequency: world("ads", "ad frequency", "promotions"),
  brandDealsPace: world("ads", "brand deals", "sponsored posts", "paid partnership"),
  inlineAdsSteering: world("ads", "personalized ads", "random ads"),
  inlineAdsPreferredTags: world("ads", "ad tags", "interests"),
  inlineAdsContentCeiling: world("ads", "ad rating", "content ceiling"),
  inlineAdsTone: world("ads", "ad voice", "tone"),
  inlineAdsEra: world("ads", "ad era", "style"),
  inlineAdsWorldContext: world("ads", "ad world", "context"),
  inlineAdsImagesEnabled: world("ads", "ad images", "pictures"),
  inlineAdsImageConnectionId: world("ads", "ad image connection", "image model"),
  inlineAdsLorebookId: world("ads", "ad lorebook"),
  inlineAdsLorebookRevision: internal(world("ads", "ad lorebook revision")),
  walletEnabled: world("wallet", "coins", "wallet", "economy"),
  walletUnlockCost: world("wallet", "post price", "unlock cost"),
  walletSubscriptionCost: world("wallet", "subscription price"),
  pricingDynamicCharacters: world("wallet", "dynamic pricing"),
  pricingMaxWeeklyChangePercent: world("wallet", "weekly price change"),
  walletStipendFloor: world("wallet", "stipend", "balance floor"),
  walletDayStartHour: world("wallet", "wallet day", "reset hour"),
  walletAdReward: world("wallet", "ad reward"),
  walletAdDailyCap: world("wallet", "daily ad cap"),
  walletEngagementReward: world("wallet", "engagement reward"),
  walletEngagementDailyCap: world("wallet", "engagement cap"),
  walletCreatorRevenueSharePercent: world("wallet", "creator revenue share"),
  imageWidth: automation("images", "post image width", "resolution"),
  imageHeight: automation("images", "post image height", "resolution"),
  storyRate: automation("general", "story posts", "story rate"),
  storyImagesEnabled: automation("general", "story posts", "image stories"),
  storyLifetimeHours: automation("general", "story lifetime", "moments"),
  teaserRate: automation("general", "teaser", "free posts", "fish for subscribers"),
  projectRate: content("storylines", "storyline", "plans", "plan rate"),
  arcPace: content("storylines", "storyline", "plan pace", "story speed"),
  arcAffectsMood: content("storylines", "storyline", "plan mood"),
  arcFanReactions: content("storylines", "storyline", "plan fan reactions"),
  arcAutoMode: content("storylines", "storyline", "automatic plans", "story suggestions"),
  arcCooldownWeeks: content("storylines", "storyline", "plan cooldown"),
  arcSource: content("storylines", "storyline", "plan source", "generated stories"),
  arcMaxConcurrentAuto: content("storylines", "storyline", "concurrent plans"),
  arcDirectorMode: content("storylines", "storyline", "plan director"),
  arcPollHours: content("storylines", "storyline", "plan polling"),
  arcStatEffects: content("storylines", "storyline", "plan stat effects"),
  arcCrossovers: content("storylines", "storyline", "plan crossovers"),
  arcLibrary: content("arcs", "plan templates", "stories"),
  contentPacks: content(
    "packs",
    "content packs",
    "slurpcon",
    "awards",
    "birthday",
    "pride",
    "exam week",
    "spicy firsts",
  ),
  discoveryTags: world("tags", "tags", "discovery", "categories"),
  storyImageWidth: automation("images", "story image width", "resolution"),
  storyImageHeight: automation("images", "story image height", "resolution"),
  refreshesPerDay: internal(automation("general", "refreshes per day", "generation")),
  generationGuidance: prompts("writing guidance", "spice", "tone"),
  audienceTone: world("audience", "audience tone", "comments"),
  worldActivity: world("audience", "world activity", "crowd activity"),
  platformScale: world("audience", "platform scale", "audience size"),
  postsPerDay: automation("general", "posts per day", "publishing pace"),
  autoPostingScheduleEnabled: automation("general", "automatic publishing", "schedule"),
  autoPostGenerationMode: automation("general", "prepare posts", "on demand"),
  fanActivityEnabled: world("audience", "fan activity", "background audience"),
  generationConnectionId: place("models", "connections", "all-slurp", "text connection", "model"),
  imageContextMode: automation("images", "image context", "vision"),
  imageContextConnectionId: automation("images", "vision connection", "image description"),
  pageConnectionId: place("models", "connections", "all-slurp", "creator pages connection", "page builder"),
  imageStyleProfileId: automation("images", "image style", "style profile"),
  imageGenerationPrompt: prompts("image instructions", "image prompt"),
  imagePromptInterpretation: prompts("image prompt interpretation", "image prompt style", "Danbooru"),
  enableImageInterpretation: automation("images", "enhance image prompts", "interpret image prompts"),
  imagePromptConnectionId: automation("images", "prompt model", "enhance image prompts"),
  imageGenerationUseAvatarReferences: automation("images", "avatar references"),
  appearanceProfileMode: automation("images", "appearance profiles", "auto accept appearance"),
  imageGenerationIncludeDescriptions: automation("images", "image descriptions"),
  imageAppearanceMode: automation("images", "look in prompts", "appearance twice", "insert appearance"),
  autoPostingImagesEnabled: automation("images", "automatic post images"),
  allowRandomUsers: world("audience", "random users", "ambient fans"),
  allowProfessorMari: internal(automation("general", "Professor Mari", "participants")),
  audienceCharacters: world("audience", "audience characters", "invited characters", "characters as fans"),
  audienceCharacterGroupIds: world("audience", "audience character groups", "invited character groups"),
  audienceCharacterLimit: world("audience", "audience character limit", "invited character limit"),
  carryoverModes: place("models", "connections", "all-slurp", "carryover", "Engine chats"),
  carryoverHours: place("models", "connections", "all-slurp", "carryover hours"),
  carryoverMaxItems: place("models", "connections", "all-slurp", "carryover limit"),
  postMaxLength: automation("general", "post length", "maximum post length"),
  postShowMoreLength: automation("general", "show more", "post preview length"),
  characterImageInstructions: place("creators", "creators", "creator", "character image instructions"),
  creatorImageNames: place("creators", "creators", "creator", "image model knows", "character name in pictures"),
  creatorCollabs: place("creators", "creators", "creator", "collabs", "collab partners", "crossover"),
  promptPresets: prompts("prompt presets", "writing presets"),
  promptInstructions: prompts("saved instructions", "reusable instructions"),
  classicPromptBlocks: internal(prompts("classic prompt preset", "classic prompts")),
  promptBlocks: prompts("prompt block builder", "prompt order", "prompt blocks"),
  professorMariCreatorSource: automation("general", "Professor Mari creator", "new creators"),
  enableLorebookContext: prompts("lorebook context"),
  flavourFromAgents: prompts("other agents", "long-term memory", "character tracker", "world state", "persona stats"),
  postPlanner: automation("general", "post ideas", "post planner", "beats", "subjects"),
  lifeMomentRate: automation("general", "daily life", "life moments", "everyday"),
  storyJobs: automation("general", "story jobs", "what stories do", "countdown", "poll", "story mix"),
  sharedPreseed: content("storylines", "shared ideas", "world tick", "niche"),
  sharedWorldEvents: content("storylines", "slurp-wide events", "platform events"),
  enableImagePrompts: internal(automation("images", "image prompts")),
  maxImagesPerRefresh: internal(automation("images", "images per refresh")),
  maxGeneratedPostsPerRefresh: internal(automation("general", "posts per refresh")),
  maxLikesPerRefresh: internal(automation("general", "likes per refresh")),
  maxRepliesPerRefresh: internal(automation("general", "replies per refresh")),
  allowGalleryImageAttachments: automation("images", "gallery attachments"),
  previewOpensPost: automation("images", "tap preview", "open post", "cropped"),
  previewWholePictures: automation("images", "whole pictures", "crop", "cropped", "fit"),
  blurPictures: automation("images", "blur pictures", "safe for work", "sfw", "hide images", "work"),
  fanActivityRunsPerDay: world("audience", "audience runs per day"),
  audienceReactionBank: world("audience", "reaction bank", "fan replies"),
  fanLikesPerRefresh: world("audience", "fan likes per refresh"),
  fanRepliesPerRefresh: world("audience", "fan replies per refresh"),
  creatorRepliesPerDay: world("audience", "creator replies per day", "comment reply limit", "cooldown"),
  fanArchetypeWeights: world("audience", "fan type weights", "audience mix"),
  fanTypes: world("audience", "fan types", "audience personas"),
  platformEvents: content("events", "occasions", "holidays", "christmas", "halloween", "special dates"),
  storyAutomation: content("storylines", "occasion automation", "suggestions", "automatic occasions", "start events"),
  messagesAwayRepliesEnabled: world("messaging", "away replies", "automatic messages"),
  messagesReplyBubbleLimit: world("messaging", "reply bubbles", "message length"),
  messagesDefaultDmPolicy: world("messaging", "DM policy", "message access"),
  messagesDefaultRequestFee: world("messaging", "message request fee"),
  messagesDefaultPpvPrice: world("messaging", "message image price", "PPV"),
  messagesUnscheduledAlwaysReachable: world("messaging", "always reachable", "message schedule"),
  messagesHighRapportDelayMinMinutes: world("messaging", "close fan reply minimum"),
  messagesHighRapportDelayMaxMinutes: world("messaging", "close fan reply maximum"),
  messagesMediumRapportDelayMinMinutes: world("messaging", "regular fan reply minimum"),
  messagesMediumRapportDelayMaxMinutes: world("messaging", "regular fan reply maximum"),
  messagesUnknownReturnDelayMinutes: world("messaging", "unknown return delay"),
  messagesMaxReplyDelayMinutes: world("messaging", "maximum reply delay"),
  messagesRecentPostAwayMinMinutes: world("messaging", "recent post away minimum"),
  messagesRecentPostAwayMaxMinutes: world("messaging", "recent post away maximum"),
  messagesStalePostAwayMinMinutes: world("messaging", "stale post away minimum"),
  messagesStalePostAwayMaxMinutes: world("messaging", "stale post away maximum"),
  messagesViewerImageCooldownMinutes: world("messaging", "picture cooldown", "draw a picture", "cooldown"),
  messagesCoolOffMinutes: world("messaging", "cool-off", "steps away", "cooldown"),
  messagesQuoteAnswerMinutes: world("messaging", "quote", "commission", "answer delay", "thinking time"),
  messagesFanOpeners: world("messaging", "fan openers", "first message", "templates"),
  messagesCommissionOpeners: world("messaging", "commission openers", "request", "templates"),
  autopurgeEnabled: maintenance("automatic cleanup", "autopurge"),
  autopurgeRetentionValue: maintenance("retention", "keep media"),
  autopurgeRetentionUnit: maintenance("retention unit"),
  autopurgeKeepPosts: maintenance("keep posts", "media only"),
  autopurgeIncludeMessageMedia: maintenance("message media cleanup"),
  autopurgeNextRunAt: maintenance("next cleanup"),
  nightQuiet: automation("general", "quiet hours", "night"),
  simulationTuning: world("audience", "simulation tuning", "fine tune audience"),
  modelBudget: world("audience", "AI budget", "model calls"),
  supportDesk: place("stir", "stir", "all-slurp", "Slurp Support", "support desk", "tickets", "trust", "stir"),
  paused: place("overview", "overview", "all-slurp", "pause all", "pause slurp", "stop", "off", "resume"),
  polyamory: place("stir", "stir", "all-slurp", "polyamory", "throuple", "couples", "love"),
  drama: place("stir", "stir", "all-slurp", "drama", "packs", "situations", "storylines", "friends"),
  postsPerDayCustom: internal(automation("general", "posts per day", "grows with creators")),
  onboarding: internal(place("creators", "creators", "new-creators", "setup", "onboarding")),
};
