import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "dist", "package");
const manifest = JSON.parse(await fs.readFile(path.join(root, "manifest.json"), "utf8"));
assert.equal(manifest.id, "gm-notes");
assert.equal(manifest.entrypoints.agents, "agents.json");
assert.equal(manifest.restartRequired, true);
for (const entrypoint of Object.values(manifest.entrypoints)) await fs.access(path.join(root, entrypoint));
const manifestFiles = new Set((manifest.files ?? []).map((file) => file.path));
for (const entrypoint of Object.values(manifest.entrypoints)) {
  assert.ok(manifestFiles.has(entrypoint), `manifest files include entrypoint ${entrypoint}`);
}
const agents = JSON.parse(await fs.readFile(path.join(root, "agents.json"), "utf8"));
const agent = agents[0];
assert.equal(agent.id, "gm-notes");
assert.equal(agent.phase, "post_processing");
assert.equal(agent.category, "tracker");
assert.equal(agent.defaultSettings.defaultPromptTemplateName, "GM Notes");
assert.match(agent.defaultSettings.defaultPromptTemplateDescription, /reminders/u);
assert.equal(agent.defaultSettings.resultType, "gm_notes_update");
assert.equal(agent.defaultSettings.contextSize, 8);
assert.equal(agent.defaultSettings.maxTokens, 2048);
assert.equal(agent.defaultSettings.contextSources.chatHistory, true);
assert.equal(agent.defaultSettings.contextSources.trackerData, true);
assert.equal(agent.defaultInjectAsSection, false);
assert.match(agent.defaultPromptTemplate, /You maintain the GM Notes tracker/u);
assert.match(agent.defaultPromptTemplate, /Return ONLY valid JSON/u);
assert.doesNotMatch(agent.defaultPromptTemplate, /at most 20 notes/u);
const client = await fs.readFile(path.join(root, "client.js"), "utf8");
assert.doesNotMatch(client, /^import\s/mu);
assert.match(client, /tracker\.section/u);
assert.match(client, /agent-suite\.tracker-data/u);
assert.match(client, /registerTrackerData/u);
assert.match(client, /buildGmNotesAgentSuitePatch/u);
assert.match(client, /roleplay\.hud/u);
assert.match(client, /tracker-section-body/u);
assert.match(client, /editMode === "lock"/u);
assert.match(client, /editMode === "delete"/u);
assert.doesNotMatch(client, /gm-notes-native-panel/u);
assert.match(client, /modeButton\("add-mode"/u);
assert.match(client, /modeButton\("lock-mode"/u);
assert.match(client, /modeButton\("remove-mode"/u);
assert.match(client, /manual: true/u);
assert.doesNotMatch(client, /\b(?:alert|prompt|confirm)\s*\(/u);
console.log("GM Notes prepared package validated.");
