import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "dist", "package");
const manifest = JSON.parse(await fs.readFile(path.join(root, "manifest.json"), "utf8"));
assert.equal(manifest.id, "gm-notes");
assert.equal(manifest.version, "1.1.1");
assert.equal(manifest.entrypoints.agents, "agents.json");
assert.equal(manifest.restartRequired, true);
assert.deepEqual(manifest.permissions, ["agent-runtime", "chat-read", "chat-write", "routes", "storage", "ui"]);
for (const entrypoint of Object.values(manifest.entrypoints)) await fs.access(path.join(root, entrypoint));
const manifestFiles = new Set((manifest.files ?? []).map((file) => file.path));
for (const entrypoint of Object.values(manifest.entrypoints)) {
  assert.ok(manifestFiles.has(entrypoint), `manifest files include entrypoint ${entrypoint}`);
}
const agents = JSON.parse(await fs.readFile(path.join(root, "agents.json"), "utf8"));
const agent = agents[0];
assert.equal(agent.id, "gm-notes");
assert.equal(agent.phase, "post_processing");
assert.equal(agent.category, "tracker");
assert.equal(agent.defaultSettings.defaultPromptTemplateName, "GM Notes");
assert.match(agent.defaultSettings.defaultPromptTemplateDescription, /reminders/u);
assert.equal(agent.defaultSettings.resultType, "gm_notes_update");
assert.equal(agent.defaultSettings.contextSize, 8);
assert.equal(agent.defaultSettings.maxTokens, 2048);
assert.equal(agent.defaultSettings.temperature, 0);
assert.equal(agent.defaultSettings.contextSources.chatHistory, true);
assert.equal(agent.defaultSettings.contextSources.trackerData, true);
assert.equal(agent.defaultInjectAsSection, false);
assert.match(agent.defaultPromptTemplate, /GM's continuity clerk/u);
assert.match(agent.defaultPromptTemplate, /Be selective/u);
assert.match(agent.defaultPromptTemplate, /Never update or remove a locked note/u);
assert.match(agent.defaultPromptTemplate, /If forgetting a detail would not plausibly make a later response wrong or incomplete/u);
assert.match(agent.defaultPromptTemplate, /Return ONLY valid JSON/u);
assert.doesNotMatch(agent.defaultPromptTemplate, /at most 20 notes/u);
const client = await fs.readFile(path.join(root, "client.js"), "utf8");
assert.doesNotMatch(client, /^import\s/mu);
assert.match(client, /api: \{ major: 1, minMinor: 8 \}/u);
assert.match(client, /tracker\.section/u);
assert.match(client, /agent-suite\.tracker-data/u);
assert.match(client, /registerTrackerData/u);
assert.match(client, /onSaved/u);
assert.match(client, /loadState\(chatId, true\)/u);
assert.match(client, /buildGmNotesAgentSuitePatch/u);
assert.match(client, /roleplay\.hud/u);
assert.match(client, /ui\.agent-settings/u);
assert.match(client, /slot: "agent\.settings"/u);
assert.match(client, /view: "settings"/u);
assert.match(client, /tracker-section-body/u);
assert.match(client, /editMode === "lock"/u);
assert.match(client, /editMode === "delete"/u);
assert.doesNotMatch(client, /gm-notes-native-panel/u);
assert.match(client, /modeButton\("add-mode"/u);
assert.match(client, /modeButton\("lock-mode"/u);
assert.match(client, /modeButton\("remove-mode"/u);
assert.match(client, /renderBackfillSettings/u);
assert.match(client, /data-gm-notes-action="backfill"/u);
assert.doesNotMatch(client, /modeButton\("backfill"/u);
assert.match(client, /\/api\/gm-notes\/backfill\//u);
assert.match(client, /marinara_admin_secret/u);
assert.match(client, /X-Admin-Secret/u);
assert.match(client, /x-marinara-csrf/u);
assert.match(client, /runBackfill/u);
assert.match(client, /Backfill paused while generation is active/u);
assert.match(client, /Completed batches are saved/u);
assert.match(client, /manual: true/u);
assert.doesNotMatch(client, /\b(?:alert|prompt|confirm)\s*\(/u);
const server = await fs.readFile(path.join(root, "src", "server", "index.js"), "utf8");
const backfill = await fs.readFile(path.join(root, "src", "server", "backfill.js"), "utf8");
const routes = await fs.readFile(path.join(root, "src", "server", "routes.js"), "utf8");
assert.match(server, /registerPrivilegedRoutes/u);
assert.match(server, /host\.request/u);
assert.match(backfill, /BACKFILL_BATCH_MESSAGES = 8/u);
assert.match(backfill, /checkpointMessageId/u);
assert.match(backfill, /mutableNoteIds/u);
assert.match(routes, /post\("\/backfill\/:chatId"/u);
assert.match(routes, /gm_notes_backfill_cancelled/u);
console.log("GM Notes prepared package validated.");
