import { useEffect, useState } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import i18next from "i18next";
import { I18nextProvider, initReactI18next } from "react-i18next";
import english from "./localization/locales/en.json";
import german from "./localization/locales/de.json";
import korean from "./localization/locales/ko.json";
import polish from "./localization/locales/pl.json";
import { SlurpHome } from "./components/slurp/SlurpHome";
import { useSlurpUIStore } from "./stores/slurp-package.store";
import { configureSlurpPackageState } from "./stores/slurp-package.store";
import { ModalPortalContext } from "./components/ui/Modal";

const SLURP_ELEMENT_TAG = "marinara-capability-slurp";
const SLURP_STYLE_ID = "marinara-capability-slurp-styles";
const client = new QueryClient({
  defaultOptions: { queries: { retry: false } },
});
const localization = i18next.createInstance();

void localization.use(initReactI18next).init({
  fallbackLng: "en",
  interpolation: { escapeValue: false },
  lng: "en",
  resources: {
    de: { translation: german },
    en: { translation: english },
    ko: { translation: korean },
    pl: { translation: polish },
  },
});

type CapabilityElement = HTMLElement & {
  capabilityProps?: Record<string, unknown>;
  __root?: Root | null;
  __portal?: HTMLDivElement | null;
};

let slurpPackageStyles = "";

function syncSlurpPackageStyles() {
  const existing = document.getElementById(SLURP_STYLE_ID);
  if (!document.querySelector(SLURP_ELEMENT_TAG) || !slurpPackageStyles) {
    existing?.remove();
    return;
  }

  const style = existing ?? document.createElement("style");
  style.id = SLURP_STYLE_ID;
  style.textContent = slurpPackageStyles;
  if (!existing) document.head.appendChild(style);
}

/** Supplies the package-scoped stylesheet generated by the catalog build. */
export function setSlurpPackageStyles(styleText: string) {
  slurpPackageStyles = styleText;
  syncSlurpPackageStyles();
}

function requestedLanguage(element: CapabilityElement) {
  const localizationContext = element.capabilityProps?.localization;
  if (!localizationContext || typeof localizationContext !== "object" || Array.isArray(localizationContext)) {
    return "en";
  }

  const locale = (localizationContext as Record<string, unknown>).locale;
  return typeof locale === "string" ? locale.split("-")[0] : "en";
}

function SlurpPackageRoot({ element }: { element: CapabilityElement }) {
  const [revision, redraw] = useState(0);
  const navigation = useSlurpUIStore((state) => state.navigation);
  const setNavigation = useSlurpUIStore((state) => state.setNavigation);

  useEffect(() => {
    configureSlurpPackageState(element.capabilityProps ?? {});
    const update = () => redraw((value) => value + 1);
    element.addEventListener("marinara-capability-props", update);
    return () => element.removeEventListener("marinara-capability-props", update);
  }, [element]);

  useEffect(() => {
    const language = requestedLanguage(element);
    const supportedLanguages = new Set(Object.keys(localization.options.resources ?? {}));
    void localization.changeLanguage(supportedLanguages.has(language) ? language : "en");
  }, [element, revision]);

  return (
    <I18nextProvider i18n={localization}>
      <QueryClientProvider client={client}>
        <ModalPortalContext.Provider value={element.__portal ?? element}>
          <div className="h-full min-h-0 overflow-hidden bg-[var(--background)] text-[var(--foreground)]">
            <SlurpHome navigation={navigation} onNavigate={setNavigation} />
          </div>
        </ModalPortalContext.Provider>
      </QueryClientProvider>
    </I18nextProvider>
  );
}

class MarinaraSlurpElement extends HTMLElement {
  declare __root: Root | null;
  declare __portal: HTMLDivElement | null;

  connectedCallback() {
    syncSlurpPackageStyles();
    if (!this.__portal) {
      this.__portal = document.createElement("div");
      this.__portal.dataset.marinaraCapabilityScope = "slurp";
      Object.assign(this.__portal.style, {
        inset: "0",
        pointerEvents: "none",
        position: "fixed",
        zIndex: "2147483000",
      });
      document.body.appendChild(this.__portal);
    }
    this.__root ??= createRoot(this);
    this.__root.render(<SlurpPackageRoot element={this} />);
  }

  disconnectedCallback() {
    queueMicrotask(() => {
      if (!this.isConnected && this.__root) {
        this.__root.unmount();
        this.__root = null;
      }
      if (!this.isConnected && this.__portal) {
        this.__portal.remove();
        this.__portal = null;
      }
      syncSlurpPackageStyles();
    });
  }
}

if (!customElements.get(SLURP_ELEMENT_TAG)) {
  customElements.define(SLURP_ELEMENT_TAG, MarinaraSlurpElement);
}
