import assert from "node:assert/strict";
import fs from "node:fs";
const root = new URL("../dist/package/", import.meta.url);
const manifest = JSON.parse(fs.readFileSync(new URL("manifest.json", root)));
const client = fs.readFileSync(new URL("client.js", root), "utf8");
assert.equal(manifest.id, "better-impersonate");
assert.equal(manifest.version, "3.0.0");
assert.deepEqual(manifest.entrypoints, { client: "client.js" });
assert.equal(manifest.contributions, undefined);
assert(!client.includes("_mari-bridge"));
assert(!client.includes("impersonateContinuation"));
assert(!client.includes("/impersonate_draft"));
assert(client.includes('data-chat-input-popup="quick-reply"'));
assert(client.includes("/generate/dryRun"));
console.log("Browser-only distribution validated.");
