import {
  garnishBrandId,
  type GarnishAd,
  type GarnishBrand,
  type GarnishContentRating,
  type GarnishPriceFeel,
} from "./garnish-ads.types.js";

type BaseProduct = {
  id: string;
  name: string;
  pitch: string;
  priceFeel: GarnishPriceFeel;
  rating: GarnishContentRating;
  categories: string[];
  contextTags: string[];
  look: string;
  actionLabel: string;
};
type BaseBrand = Omit<GarnishBrand, "id" | "platform" | "origin"> & { products: BaseProduct[] };

/**
 * Shipped parody brands. Every one is made up; the jokes are the point. Adult ones carry an honest
 * rating, so the host's ceiling decides whether they show at all.
 */
const BASE_BRANDS: readonly BaseBrand[] = [
  {
    name: "Nightjar Coffee",
    category: "coffee",
    tone: "Dry, a little moody, for people who work when everyone else sleeps.",
    logoPrompt: "a small nightjar bird silhouette over a coffee bean, deep navy and cream",
    products: [],
  },
  {
    name: "Moonmilk Beauty",
    category: "beauty",
    tone: "Soft, dreamy, whispered like a bedtime ritual.",
    logoPrompt: "a crescent moon dripping into a milk drop, pearl white and lilac",
    products: [],
  },
  {
    name: "Black Halo Rooms",
    category: "nightlife",
    tone: "Discreet and expensive. Says very little.",
    logoPrompt: "a thin black ring with a soft glow behind it, matte black and gold",
    products: [],
  },
  {
    name: "Bepis",
    category: "drinks",
    tone: "Loud, sugary, retro mascot energy. Proudly the other cola.",
    logoPrompt: "a round red, white and blue cola badge with a wobbly smile, bold bubbly letters shape",
    products: [
      {
        id: "bepis-classic",
        name: "Bepis Classic",
        pitch: "It is not the one you were thinking of. It is better. Probably.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["drinks", "food", "snack"],
        contextTags: ["summer", "party", "games"],
        look: "a sweating blue cola can with a round red and white badge, ice cubes around it",
        actionLabel: "Crack one open",
      },
      {
        id: "bepis-zero-regrets",
        name: "Bepis Zero Regrets",
        pitch: "Zero sugar. Zero calories. Some regrets, but fewer.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["drinks", "fitness"],
        contextTags: ["gym", "summer"],
        look: "a matte black cola can with a silver badge, cold droplets on it",
        actionLabel: "Try Zero",
      },
    ],
  },
  {
    name: "Gamerfuel",
    category: "gaming",
    tone: "ALL CAPS hype, fake science, 'unlock your final form'.",
    logoPrompt: "a neon green lightning bolt inside a hexagon, glowing edges",
    products: [
      {
        id: "gamerfuel-ranked-rage",
        name: "Gamerfuel Ranked Rage",
        pitch: "400 mg of pure focus. Your heart rate is now a feature.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["gaming", "games", "drinks"],
        contextTags: ["stream", "night", "late-night"],
        look: "a tall neon green energy drink can with a lightning bolt, glowing next to a keyboard",
        actionLabel: "Fuel up",
      },
      {
        id: "gamerfuel-powder-tub",
        name: "Gamerfuel Powder Tub",
        pitch: "Mix it, shake it, speedrun your sleep schedule. 60 servings of chaos.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["gaming", "games"],
        contextTags: ["stream", "working"],
        look: "a chunky black tub of drink powder with a neon green scoop and a shaker bottle",
        actionLabel: "Grab a tub",
      },
    ],
  },
  {
    name: "McNoodles",
    category: "fast food",
    tone: "Cheerful mascot voice, puns everywhere. I'm slurpin' it.",
    logoPrompt: "two golden ramen arches forming an M, on a red square",
    products: [
      {
        id: "mcnoodles-big-slurp",
        name: "Big Slurp Bowl",
        pitch: "Two layers of ramen, special sauce, a bowl the size of your problems.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["food", "fast food"],
        contextTags: ["night", "city", "party"],
        look: "a huge paper ramen bowl with golden arches, steam rising, chopsticks stuck in",
        actionLabel: "Order now",
      },
      {
        id: "mcnoodles-midnight-menu",
        name: "Midnight Menu",
        pitch: "Open till 4. We do not judge. We do not remember.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["food", "late-night", "nightlife"],
        contextTags: ["night", "club", "late-night"],
        look: "a paper bag of ramen nuggets and fries on a car seat under street lights",
        actionLabel: "See the menu",
      },
    ],
  },
  {
    name: "Silk & Sin",
    category: "lingerie",
    tone: "Sultry, confident, a wink in every line.",
    logoPrompt: "an elegant ribbon tied into an ampersand, black satin on blush pink",
    products: [
      {
        id: "silk-and-sin-confession-set",
        name: "Confession Lace Set",
        pitch: "Delicate lace for the things you only say after midnight.",
        priceFeel: "premium",
        rating: "suggestive",
        categories: ["lingerie", "style", "fashion"],
        contextTags: ["date", "night", "home"],
        look: "a black lace bra and panty set laid on crumpled satin sheets",
        actionLabel: "Shop the set",
      },
      {
        id: "silk-and-sin-lazy-sunday-robe",
        name: "Lazy Sunday Robe",
        pitch: "Silk that makes doing nothing look like a choice.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["lingerie", "style", "fashion", "home"],
        contextTags: ["home", "morning"],
        look: "a blush pink silk robe on a hanger in morning light",
        actionLabel: "Shop robes",
      },
    ],
  },
  {
    name: "Buzzworthy",
    category: "adult toys",
    tone: "Cheeky, sex-positive, zero shame, lots of bee puns.",
    logoPrompt: "a cute bee with a heart-shaped body, honey yellow and hot pink",
    products: [
      {
        id: "buzzworthy-honeybee-wand",
        name: "The Honeybee Wand",
        pitch: "Ten speeds, one very busy evening. Whisper quiet, neighbours none the wiser.",
        priceFeel: "premium",
        rating: "explicit",
        categories: ["adult toys", "toys", "wellness"],
        contextTags: ["night", "home", "date"],
        look: "a sleek honey yellow wand massager on a pink silk pillow",
        actionLabel: "Get buzzing",
      },
      {
        id: "buzzworthy-first-buzz-kit",
        name: "First Buzz Starter Kit",
        pitch: "Your first toy should be fun, not scary. Three small friends in a cute box.",
        priceFeel: "everyday",
        rating: "suggestive",
        categories: ["adult toys", "toys", "wellness"],
        contextTags: ["home", "date"],
        look: "a honeycomb-patterned gift box with three small pastel toys nestled inside",
        actionLabel: "See the kit",
      },
    ],
  },
  {
    name: "Gains Goblin",
    category: "fitness",
    tone: "Gym-bro chaos with a heart of gold. Every rep is a quest.",
    logoPrompt: "a grinning green goblin flexing one arm, bold cartoon style",
    products: [
      {
        id: "gains-goblin-whey",
        name: "Goblin Whey",
        pitch: "Tastes like cookies, lifts like a curse. 30 g protein per scoop.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["fitness", "gym", "food"],
        contextTags: ["gym", "morning", "summer"],
        look: "a big green protein tub with a goblin face, a scoop of powder beside it",
        actionLabel: "Stack gains",
      },
      {
        id: "gains-goblin-squat-leggings",
        name: "Squat-Proof Leggings",
        pitch: "Tested on 10,000 squats and one very honest mirror.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["fitness", "style", "fashion"],
        contextTags: ["gym", "summer"],
        look: "high-waisted forest green gym leggings folded on a bench next to dumbbells",
        actionLabel: "Shop leggings",
      },
    ],
  },
  {
    name: "Throne Gaming",
    category: "gaming chair",
    tone: "Over-the-top royal. You do not sit, you reign.",
    logoPrompt: "a crown on top of a gaming chair outline, red and black with RGB glow",
    products: [
      {
        id: "throne-gaming-x9000",
        name: "Throne X9000",
        pitch: "Lumbar support for 14-hour sessions. RGB so bright it counts as a lamp.",
        priceFeel: "premium",
        rating: "tame",
        categories: ["gaming", "games", "setup"],
        contextTags: ["stream", "working", "night"],
        look: "a red and black racing-style gaming chair with RGB strips in a dark streaming room",
        actionLabel: "Claim your throne",
      },
    ],
  },
  {
    name: "Swipr",
    category: "dating app",
    tone: "Flirty, a little desperate, emoji-heavy.",
    logoPrompt: "a flame shaped like a swipe arrow, coral to magenta gradient",
    products: [
      {
        id: "swipr-gold",
        name: "Swipr Gold",
        pitch: "See who liked you. Spoiler: it is mostly people from your gym.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["dating", "social", "nightlife"],
        contextTags: ["date", "city", "night"],
        look: "a glossy gold card with a coral flame symbol, confetti around it",
        actionLabel: "Go Gold",
      },
      {
        id: "swipr-after-dark",
        name: "Swipr After Dark",
        pitch: "For when 'wyd' means exactly what you think it means.",
        priceFeel: "everyday",
        rating: "suggestive",
        categories: ["dating", "nightlife"],
        contextTags: ["night", "late-night", "date"],
        look: "a dark magenta neon flame symbol glowing on a bedside table at night",
        actionLabel: "Swipe after dark",
      },
    ],
  },
  {
    name: "Pawsome Chow",
    category: "pet food",
    tone: "Wholesome pet-food commercial voice, aimed squarely at furries.",
    logoPrompt: "a smiling paw print holding a fork, warm orange and cream",
    products: [
      {
        id: "pawsome-chow-kibble-for-grownups",
        name: "Kibble for Grown-Ups",
        pitch: "Human-grade crunch in a bowl with your name on it. Good fur, good boy, good girl.",
        priceFeel: "budget",
        rating: "tame",
        categories: ["furry", "anthro", "food", "snack"],
        contextTags: ["home", "convention"],
        look: "a ceramic pet bowl with a name tag full of fancy kibble-shaped snacks",
        actionLabel: "Fill your bowl",
      },
      {
        id: "pawsome-chow-tail-shine",
        name: "Tail Shine Conditioner",
        pitch: "Fluff that turns heads at every con. Tangles need not apply.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["furry", "anthro", "beauty"],
        contextTags: ["convention", "home"],
        look: "a bottle of glossy fur conditioner next to a soft grooming brush and fluffy tuft",
        actionLabel: "Get the shine",
      },
    ],
  },
  {
    name: "SneakyTunnel",
    category: "vpn",
    tone: "Paranoid podcast-sponsor read. We keep no logs (we keep some logs).",
    logoPrompt: "a cartoon mole in sunglasses peeking out of a tunnel, teal and black",
    products: [
      {
        id: "sneakytunnel-premium",
        name: "SneakyTunnel Premium",
        pitch: "Browse from 94 countries. Your ISP will never know. Your mum might.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["tech", "privacy", "games"],
        contextTags: ["working", "stream", "travel"],
        look: "a glowing teal shield icon over a laptop in a dark room, a tiny mole mascot on the lid",
        actionLabel: "Go sneaky",
      },
    ],
  },
  {
    name: "Thirst Trap Studio",
    category: "creator gear",
    tone: "Influencer-coach energy. Lighting is a personality.",
    logoPrompt: "a ring light shaped like a glossy lip print, soft white and peach",
    products: [
      {
        id: "thirst-trap-glow-ring",
        name: "Glow Ring 18",
        pitch: "Flattering light from every angle. Your good side is now every side.",
        priceFeel: "everyday",
        rating: "tame",
        categories: ["beauty", "creator", "style"],
        contextTags: ["home", "stream"],
        look: "a large ring light glowing softly in a cosy bedroom corner",
        actionLabel: "Light it up",
      },
    ],
  },
];

/** Shipped brands. Each host falls back to these when nothing else exists. */
export const GARNISH_BASE_BRANDS: readonly GarnishBrand[] = BASE_BRANDS.map(({ products: _products, ...brand }) => ({
  ...brand,
  id: garnishBrandId(brand.name),
  platform: "slurp",
  origin: "builtin",
}));

/** Shipped base pool. Each host falls back to this when nothing else exists. */
export const GARNISH_BASE_ADS: readonly GarnishAd[] = [
  {
    id: "nightjar-midnight-blend",
    platform: "slurp",
    kind: "inline",
    contentRating: "tame",
    origin: "builtin",
    brand: "Nightjar Coffee",
    brandId: garnishBrandId("Nightjar Coffee"),
    product: "Midnight Blend",
    copy: "A bitter little ritual for people who refuse to sleep on schedule.",
    categories: ["coffee", "late-night", "work"],
    contextTags: ["night", "rain", "working"],
    actionLabel: "View blend",
    priceFeel: "everyday",
    look: "a dark roast coffee bag with a small bird on it next to a steaming mug at night",
  },
  {
    id: "moonmilk-afterglow",
    platform: "slurp",
    kind: "inline",
    contentRating: "tame",
    origin: "builtin",
    brand: "Moonmilk Beauty",
    brandId: garnishBrandId("Moonmilk Beauty"),
    product: "Afterglow Night Set",
    copy: "Soft floral light for routines that happen long after midnight.",
    categories: ["beauty", "luxury", "night"],
    contextTags: ["night", "home", "date"],
    actionLabel: "View set",
    priceFeel: "premium",
    look: "pearl glass skincare bottles with a lilac moon label on a vanity at night",
  },
  {
    id: "black-halo-private-rooms",
    platform: "slurp",
    kind: "inline",
    contentRating: "tame",
    origin: "builtin",
    brand: "Black Halo Rooms",
    brandId: garnishBrandId("Black Halo Rooms"),
    product: "After-hours private rooms",
    copy: "The city is loud. Your reservation does not have to be.",
    categories: ["nightlife", "private", "luxury"],
    contextTags: ["night", "club", "city"],
    actionLabel: "See rooms",
    priceFeel: "premium",
    look: "a dim velvet lounge room with a soft gold ring light on the wall",
  },
  ...BASE_BRANDS.flatMap((brand) =>
    brand.products.map((product): GarnishAd => ({
      id: product.id,
      platform: "slurp",
      kind: "inline",
      contentRating: product.rating,
      origin: "builtin",
      brand: brand.name,
      brandId: garnishBrandId(brand.name),
      product: product.name,
      copy: product.pitch,
      categories: product.categories,
      contextTags: product.contextTags,
      actionLabel: product.actionLabel,
      priceFeel: product.priceFeel,
      look: product.look,
    })),
  ),
];
